export const StateArray = [
  { key: 1, state: "Alabama" },
  { key: 2, state: "Alaska" },
  { key: 3, state: "Arizona" },
  { key: 4, state: "Arkansas" },
  { key: 5, state: "California" },
  { key: 6, state: "Colorado" },
  { key: 7, state: "Connecticut" },
  { key: 8, state: "Delaware" },
  { key: 9, state: "Florida" },
  { key: 10, state: "Georgia" },
  { key: 11, state: "Hawaii" },
  { key: 12, state: "Idaho" },
  { key: 13, state: "Illinois" },
  { key: 14, state: "Indiana" },
  { key: 15, state: "Iowa" },
  { key: 16, state: "Kansas" },
  { key: 17, state: "Kentucky" },
  { key: 18, state: "Louisiana" },
  { key: 19, state: "Maine" },
  { key: 20, state: "Maryland" },
  { key: 21, state: "Massachusetts" },
  { key: 22, state: "Michigan" },
  { key: 23, state: "Minnesota" },
  { key: 24, state: "Mississippi" },
  { key: 25, state: "Missouri" },
  { key: 26, state: "Montana" },
  { key: 27, state: "Nebraska" },
  { key: 28, state: "Nevada" },
  { key: 29, state: "New Hampshire" },
  { key: 30, state: "New Jersey" },
  { key: 31, state: "New Mexico" },
  { key: 32, state: "New York" },
  { key: 33, state: "North Carolina" },
  { key: 34, state: "North Dakota" },
  { key: 35, state: "Ohio" },
  { key: 36, state: "Oklahoma" },
  { key: 37, state: "Oregon" },
  { key: 38, state: "Pennsylvania" },
  { key: 39, state: "Rhode Island" },
  { key: 40, state: "South Carolina" },
  { key: 41, state: "South Dakota" },
  { key: 42, state: "Tennessee" },
  { key: 43, state: "Texas" },
  { key: 44, state: "Utah" },
  { key: 45, state: "Vermont" },
  { key: 46, state: "Virginia" },
  { key: 47, state: "Washington" },
  { key: 48, state: "West Virginia" },
  { key: 49, state: "Wisconsin" },
  { key: 50, state: "Wyoming" },
];
